# Generated by Django 2.2 on 2021-05-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='magazine',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_magazines', to='app_three.User'),
        ),
    ]
